CREATE TABLE IF NOT EXISTS public.acquisition_attributions (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    gclid TEXT,
    gbraid TEXT,
    wbraid TEXT,
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    utm_term TEXT,
    utm_content TEXT,
    campaign_id TEXT,
    ad_group_id TEXT,
    creative_id TEXT,
    device TEXT,
    network TEXT,
    match_type TEXT,
    landing_path TEXT,
    referrer TEXT,
    user_agent TEXT,
    intended_platform TEXT CHECK (intended_platform IS NULL OR intended_platform IN ('win32', 'darwin')),
    download_clicked_at TIMESTAMPTZ,
    node_identifier TEXT,
    node_platform TEXT CHECK (node_platform IS NULL OR node_platform IN ('win32', 'darwin')),
    node_connected_at TIMESTAMPTZ,
    node_baseline_requests BIGINT NOT NULL DEFAULT 0,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS acquisition_attributions_gclid_idx
    ON public.acquisition_attributions(gclid)
    WHERE gclid IS NOT NULL;
CREATE INDEX IF NOT EXISTS acquisition_attributions_user_id_idx
    ON public.acquisition_attributions(user_id)
    WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS acquisition_attributions_node_identifier_idx
    ON public.acquisition_attributions(node_identifier)
    WHERE node_identifier IS NOT NULL;
CREATE INDEX IF NOT EXISTS acquisition_attributions_campaign_id_idx
    ON public.acquisition_attributions(campaign_id, first_seen_at DESC);

CREATE TABLE IF NOT EXISTS public.acquisition_node_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribution_id UUID NOT NULL REFERENCES public.acquisition_attributions(id) ON DELETE CASCADE,
    node_identifier TEXT NOT NULL,
    snapshot_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_requests BIGINT NOT NULL DEFAULT 0,
    opt_in BOOLEAN,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (attribution_id, snapshot_date)
);

CREATE INDEX IF NOT EXISTS acquisition_node_snapshots_lookup_idx
    ON public.acquisition_node_snapshots(attribution_id, snapshot_date);

CREATE TABLE IF NOT EXISTS public.acquisition_retention_milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribution_id UUID NOT NULL REFERENCES public.acquisition_attributions(id) ON DELETE CASCADE,
    milestone_days SMALLINT NOT NULL CHECK (milestone_days IN (14, 30, 90)),
    active BOOLEAN NOT NULL,
    requests_in_lookback BIGINT NOT NULL DEFAULT 0,
    requests_since_install BIGINT NOT NULL DEFAULT 0,
    evaluated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (attribution_id, milestone_days)
);

CREATE TABLE IF NOT EXISTS public.acquisition_conversions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribution_id UUID NOT NULL REFERENCES public.acquisition_attributions(id) ON DELETE CASCADE,
    milestone TEXT NOT NULL CHECK (milestone IN ('desktop_node_connected', 'active_14d', 'active_30d')),
    conversion_at TIMESTAMPTZ NOT NULL,
    conversion_value NUMERIC(12, 6) NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'EUR',
    order_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (attribution_id, milestone),
    UNIQUE (order_id)
);

CREATE TABLE IF NOT EXISTS public.acquisition_campaign_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_date DATE NOT NULL,
    campaign_id TEXT NOT NULL,
    ad_group_id TEXT NOT NULL DEFAULT '',
    cost NUMERIC(12, 4) NOT NULL CHECK (cost >= 0),
    currency TEXT NOT NULL DEFAULT 'EUR',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (cost_date, campaign_id, ad_group_id, currency)
);

ALTER TABLE public.acquisition_attributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acquisition_node_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acquisition_retention_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acquisition_conversions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acquisition_campaign_costs ENABLE ROW LEVEL SECURITY;

-- These tables intentionally have no client policies. Reads and writes go through
-- authenticated server routes using the service role because click IDs are sensitive.

CREATE OR REPLACE VIEW public.acquisition_campaign_performance AS
WITH attribution_rollup AS (
    SELECT
        COALESCE(a.campaign_id, a.utm_campaign, '(unassigned)') AS campaign_key,
        MAX(a.utm_campaign) AS campaign_name,
        COUNT(*) AS attributed_visits,
        COUNT(*) FILTER (WHERE a.download_clicked_at IS NOT NULL) AS downloads,
        COUNT(*) FILTER (WHERE a.node_connected_at IS NOT NULL) AS desktop_nodes,
        COUNT(r14.id) AS evaluated_14d,
        COUNT(r30.id) AS evaluated_30d,
        COUNT(r90.id) AS evaluated_90d,
        COUNT(*) FILTER (WHERE r14.active) AS active_14d,
        COUNT(*) FILTER (WHERE r30.active) AS active_30d,
        COUNT(*) FILTER (WHERE r90.active) AS active_90d,
        COALESCE(SUM(r14.requests_since_install), 0) AS requests_14d,
        COALESCE(SUM(r30.requests_since_install), 0) AS requests_30d,
        COALESCE(SUM(r90.requests_since_install), 0) AS requests_90d
    FROM public.acquisition_attributions a
    LEFT JOIN public.acquisition_retention_milestones r14
        ON r14.attribution_id = a.id AND r14.milestone_days = 14
    LEFT JOIN public.acquisition_retention_milestones r30
        ON r30.attribution_id = a.id AND r30.milestone_days = 30
    LEFT JOIN public.acquisition_retention_milestones r90
        ON r90.attribution_id = a.id AND r90.milestone_days = 90
    GROUP BY COALESCE(a.campaign_id, a.utm_campaign, '(unassigned)')
),
cost_rollup AS (
    SELECT campaign_id AS campaign_key, SUM(cost) AS spend, MAX(currency) AS currency
    FROM public.acquisition_campaign_costs
    GROUP BY campaign_id
)
SELECT
    a.*,
    COALESCE(c.spend, 0) AS spend,
    COALESCE(c.currency, 'EUR') AS currency,
    CASE WHEN a.desktop_nodes > 0 THEN COALESCE(c.spend, 0) / a.desktop_nodes ELSE NULL END AS desktop_node_cac,
    CASE WHEN a.evaluated_14d > 0 THEN (a.requests_14d / 1000.0 * 0.27) / a.evaluated_14d ELSE NULL END AS gross_ltv_14d_eur,
    CASE WHEN a.evaluated_30d > 0 THEN (a.requests_30d / 1000.0 * 0.27) / a.evaluated_30d ELSE NULL END AS gross_ltv_30d_eur,
    CASE WHEN a.evaluated_90d > 0 THEN (a.requests_90d / 1000.0 * 0.27) / a.evaluated_90d ELSE NULL END AS gross_ltv_90d_eur
FROM attribution_rollup a
LEFT JOIN cost_rollup c USING (campaign_key);

COMMENT ON VIEW public.acquisition_campaign_performance IS
    'Paid acquisition funnel and gross request-value proxy by campaign. The 0.27 EUR/1k request rate must be updated if realized monetization changes.';

REVOKE ALL ON public.acquisition_attributions FROM anon, authenticated;
REVOKE ALL ON public.acquisition_node_snapshots FROM anon, authenticated;
REVOKE ALL ON public.acquisition_retention_milestones FROM anon, authenticated;
REVOKE ALL ON public.acquisition_conversions FROM anon, authenticated;
REVOKE ALL ON public.acquisition_campaign_costs FROM anon, authenticated;
REVOKE ALL ON public.acquisition_campaign_performance FROM anon, authenticated;
